name: UA-Purchasing-System docs
markdown: redcarpet
redcarpet:
    fenced_code_blocks: true
    extensions: 
        - no_intra_emphasis
        - fenced_code_blocks
        - autolink
        - tables
        - with_toc_data
pygments: true
permalink: /posts/:year/:month/:day/:title.html
baseurl: /UA-purchasing-system
